# Schema for the configuration files of the Optimizedb module.

optimizedb.settings:
  type: mapping
  label: 'Optimizedb settings'
  mapping:
    last_optimization:
      type: integer
      label: 'Timestamp last optimization'
    optimization_period:
      type: integer
      label: 'Optimization period in days.'
    tables_size:
      type: integer
      label: 'Size of all site tables.'
    notify_optimize:
      type: boolean
      label: 'Status notify about optimization.'
